### ISSUE TITLE
Move to purescript core libraries

### ISSUE THREAD

**Issue by paf31** [paf31/purescript-parallel#1]
@garyb Is there anything missing here? I think this is pretty useful general-purpose thing which fits nicely with the `transformers` family.

**Comment by garyb** [comment]
I think we use "Copyright (c) 2014 PureScript" in the license file for most of the core libraries, but not sure if that even matters. Looks all good to me. :boat:

**Comment by paf31** [comment]
Yep, I can change that.

**Comment by paf31** [comment]
Actually, come to think of it, I always wondered if that held any water in a legal sense. I know what we want it to mean, but PureScript doesn't really exist as an organization in any meaningful way. Maybe `(c) 20xx PureScript.org` would be better? At least a domain name has an associated name and address etc.

**Comment by garyb** [comment]
Yeah, I was thinking about the same thing when writing that comment above, I'm not sure what the way to go is with that.
